tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "primary-fixed-dim": "#c0c6db",
                "primary-container": "#141b2b",
                "tertiary-container": "#261906",
                "on-secondary-fixed": "#151c27",
                "tertiary": "#ffffff",
                "on-tertiary-fixed-variant": "#55442d",
                "secondary-container": "#dce2f3",
                "on-secondary": "#ffffff",
                "outline": "#76777d",
                "on-error": "#ffffff",
                "on-primary-fixed-variant": "#404758",
                "primary": "#5d3fd3",
                "on-tertiary-fixed": "#261906",
                "outline-variant": "#c6c6cd",
                "on-secondary-fixed-variant": "#404754",
                "secondary-fixed-dim": "#c0c7d6",
                "error": "#ba1a1a",
                "surface-tint": "#575e70",
                "tertiary": "#000000",
                "error-container": "#ffdad6",
                "on-surface": "#1b1b1d",
                "tertiary-fixed": "#f9debf",
                "surface-container-high": "#eae7e9",
                "on-background": "#1b1b1d",
                "on-error-container": "#93000a",
                "surface-dim": "#dcd9db",
                "surface-container": "#f0edee",
                "secondary": "#585f6c",
                "surface-bright": "#fcf8fa",
                "surface-container-highest": "#e5e2e3",
                "surface-variant": "#e5e2e3",
                "on-surface-variant": "#45464c",
                "on-primary-fixed": "#141b2b",
                "inverse-primary": "#c0c6db",
                "tertiary-fixed-dim": "#dcc2a4",
                "secondary-fixed": "#dce2f3",
                "on-tertiary-container": "#968065",
                "primary-fixed": "#dce2f7",
                "surface-container-low": "#f6f3f4",
                "background": "#fcf8fa",
                "inverse-on-surface": "#f3f0f1",
                "surface": "#fcf8fa",
                "on-tertiary": "#ffffff",
                "inverse-surface": "#303031",
                "on-primary-container": "#7d8497",
                "on-secondary-container": "#5e6572",
                "on-primary": "#ffffff"
            },
            "borderRadius": {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
            "spacing": {
                "xs": "0.25rem",
                "md": "1rem",
                "sm": "0.5rem",
                "container-max": "1280px",
                "lg": "1.5rem",
                "gutter": "24px",
                "base": "4px",
                "xl": "2rem",
                "2xl": "3rem"
            },
            "fontFamily": {
                "label-caps": ["Inter"],
                "title-md": ["Inter"],
                "body-md": ["Inter"],
                "body-sm": ["Inter"],
                "display-lg": ["Inter"],
                "headline-lg": ["Inter"],
                "headline-lg-mobile": ["Inter"]
            },
            "fontSize": {
                "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
                "title-md": ["18px", { "lineHeight": "24px", "fontWeight": "600" }],
                "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
                "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
                "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
                "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
                "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }]
            }
        }
    }
}
